In [37]:
import pandas as pd
import numpy as np
import plotly.express as px
import matplotlib.pyplot as plt

In [38]:
df= pd.read_csv('Biomass_History.csv')

In [39]:
df.head()

,Index,Latitude,Longitude,2010,2011,2012,2013,2014,2015,2016,2017
0,0,24.66818,71.33144,8.475744,8.868568,9.202181,6.023070,10.788374,6.647325,7.387925,5.180296
1,1,24.66818,71.41106,24.029778,28.551348,25.866415,21.634459,34.419411,27.361908,40.431847,42.126945
2,2,24.66818,71.49069,44.831635,66.111168,56.982258,53.003735,70.917908,42.517117,59.181629,73.203232
3,3,24.66818,71.57031,59.974419,80.821304,78.956543,63.160561,93.513924,70.203171,74.536720,101.067352
4,4,24.66818,71.64994,14.653370,19.327524,21.928144,17.899586,19.534035,19.165791,16.531315,26.086885

In [40]:
columns = ['2010','2011','2012','2013','2014','2015','2016','2017']

In [41]:
df

,Index,Latitude,Longitude,2010,2011,2012,2013,2014,2015,2016,2017
0,0,24.66818,71.33144,8.475744,8.868568,9.202181,6.023070,10.788374,6.647325,7.387925,5.180296
1,1,24.66818,71.41106,24.029778,28.551348,25.866415,21.634459,34.419411,27.361908,40.431847,42.126945
2,2,24.66818,71.49069,44.831635,66.111168,56.982258,53.003735,70.917908,42.517117,59.181629,73.203232
3,3,24.66818,71.57031,59.974419,80.821304,78.956543,63.160561,93.513924,70.203171,74.536720,101.067352
4,4,24.66818,71.64994,14.653370,19.327524,21.928144,17.899586,19.534035,19.165791,16.531315,26.086885
...,...,...,...,...,...,...,...,...,...,...,...
2413,2413,20.15456,72.84432,5.199882,4.516778,4.321080,2.658953,5.113997,5.301668,6.419223,5.321604
2414,2414,20.15456,72.92394,0.122287,0.126717,0.101494,0.111509,0.121749,0.122467,0.145785,0.120626
2415,2415,20.15456,73.00357,0.039415,0.040843,0.032713,0.035941,0.039241,0.039473,0.046989,0.038879
2416,2416,20.15456,73.08319,2.719220,1.370163,0.818687,1.205721,1.316443,1.324201,1.576338,1.304297
2417,2417,20.15456,73.16282,0.621228,0.238414,0.112909,0.209801,0.229067,0.230417,0.274289,0.226953

In [42]:
for j in range(3,9): 
    d = []
    e = []
    for i in range(len(df)):
        
        value = (df.iloc[i,j]+df.iloc[i,j+1]+df.iloc[i,j+2])/3
        fore1 = (0.1*df.iloc[i,j+2]) + (0.9*value)
        fore2  = (0.1*df.iloc[i,j+3]) + (0.9*fore1)
        d.append(fore1)
        e.append(fore2)
        
    df['fore'+ str(j)] = d
    df['fore'+str(j)+str(j)] = e

In [43]:
pd.set_option('display.max_columns', None)

In [44]:
df

,Index,Latitude,Longitude,2010,2011,2012,2013,2014,2015,2016,2017,fore3,fore33,fore4,fore44,fore5,fore55,fore6,fore66,fore7,fore77,fore8,fore88
0,0,24.66818,71.33144,8.475744,8.868568,9.202181,6.023070,10.788374,6.647325,7.387925,5.180296,8.884166,8.598057,7.830453,8.126245,8.882925,8.659365,7.702363,7.670919,8.185880,7.885321,6.282693,6.542841
1,1,24.66818,71.41106,24.029778,28.551348,25.866415,21.634459,34.419411,27.361908,40.431847,42.126945,26.120904,25.672259,24.979112,25.923142,28.018026,27.952415,27.760924,29.028016,34.707134,35.449115,37.188905,36.082104
2,2,24.66818,71.49069,44.831635,66.111168,56.982258,53.003735,70.917908,42.517117,59.181629,73.203232,56.075744,55.768543,58.129522,59.408360,61.362961,59.478376,54.183339,54.683168,57.703159,59.253166,59.790916,59.419399
3,3,24.66818,71.57031,59.974419,80.821304,78.956543,63.160561,93.513924,70.203171,74.536720,101.067352,73.821334,72.755257,73.197578,75.229213,80.040701,79.056948,75.083614,75.028924,78.929816,81.143570,83.848908,82.846151
4,4,24.66818,71.64994,14.653370,19.327524,21.928144,17.899586,19.534035,19.165791,16.531315,26.086885,18.965526,18.858932,19.536535,19.536285,19.761933,19.702319,18.896402,18.659894,18.222474,19.008915,21.143886,20.926050
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2413,2413,20.15456,72.84432,5.199882,4.516778,4.321080,2.658953,5.113997,5.301668,6.419223,5.321604,4.643430,4.444982,3.714938,3.854844,4.139609,4.255815,4.452552,4.649219,5.692389,5.655310,5.644909,5.544761
2414,2414,20.15456,72.92394,0.122287,0.126717,0.101494,0.111509,0.121749,0.122467,0.145785,0.120626,0.115299,0.114920,0.113067,0.113935,0.112601,0.113587,0.118964,0.121646,0.131579,0.130483,0.128726,0.127383
2415,2415,20.15456,73.00357,0.039415,0.040843,0.032713,0.035941,0.039241,0.039473,0.046989,0.038879,0.037162,0.037040,0.036443,0.036723,0.036293,0.036611,0.038344,0.039208,0.042410,0.042057,0.041490,0.041057
2416,2416,20.15456,73.08319,2.719220,1.370163,0.818687,1.205721,1.316443,1.324201,1.576338,1.304297,1.554290,1.519433,1.138944,1.156694,1.133900,1.152930,1.286330,1.315331,1.422729,1.410885,1.391881,1.408121
2417,2417,20.15456,73.16282,0.621228,0.238414,0.112909,0.209801,0.229067,0.230417,0.274289,0.226953,0.303056,0.293731,0.189317,0.193292,0.188440,0.192637,0.223827,0.228873,0.247561,0.245500,0.242193,0.248279

In [45]:
df['resi1(2013)'] = df['fore3'] - df['2013']
df['resi1(2014)'] = df['fore4'] - df['2014']
df['resi1(2015)'] = df['fore5'] - df['2015']
df['resi1(2016)'] = df['fore6'] - df['2016']
df['resi1(2017)'] = df['fore7'] - df['2017']

df['resi2(2014)'] = df['fore33'] - df['2014']
df['resi2(2015)'] = df['fore44'] - df['2015']
df['resi2(2016)'] = df['fore55'] - df['2016']
df['resi2(2017)'] = df['fore66'] - df['2017']

In [46]:
df

,Index,Latitude,Longitude,2010,2011,2012,2013,2014,2015,2016,2017,fore3,fore33,fore4,fore44,fore5,fore55,fore6,fore66,fore7,fore77,fore8,fore88,resi1(2013),resi1(2014),resi1(2015),resi1(2016),resi1(2017),resi2(2014),resi2(2015),resi2(2016),resi2(2017)
0,0,24.66818,71.33144,8.475744,8.868568,9.202181,6.023070,10.788374,6.647325,7.387925,5.180296,8.884166,8.598057,7.830453,8.126245,8.882925,8.659365,7.702363,7.670919,8.185880,7.885321,6.282693,6.542841,2.861096,-2.957921,2.235600,0.314438,3.005583,-2.190317,1.478920,1.271440,2.490623
1,1,24.66818,71.41106,24.029778,28.551348,25.866415,21.634459,34.419411,27.361908,40.431847,42.126945,26.120904,25.672259,24.979112,25.923142,28.018026,27.952415,27.760924,29.028016,34.707134,35.449115,37.188905,36.082104,4.486445,-9.440298,0.656118,-12.670923,-7.419811,-8.747152,-1.438766,-12.479432,-13.098929
2,2,24.66818,71.49069,44.831635,66.111168,56.982258,53.003735,70.917908,42.517117,59.181629,73.203232,56.075744,55.768543,58.129522,59.408360,61.362961,59.478376,54.183339,54.683168,57.703159,59.253166,59.790916,59.419399,3.072009,-12.788386,18.845844,-4.998290,-15.500073,-15.149365,16.891244,0.296747,-18.520064
3,3,24.66818,71.57031,59.974419,80.821304,78.956543,63.160561,93.513924,70.203171,74.536720,101.067352,73.821334,72.755257,73.197578,75.229213,80.040701,79.056948,75.083614,75.028924,78.929816,81.143570,83.848908,82.846151,10.660773,-20.316345,9.837530,0.546893,-22.137536,-20.758667,5.026042,4.520227,-26.038428
4,4,24.66818,71.64994,14.653370,19.327524,21.928144,17.899586,19.534035,19.165791,16.531315,26.086885,18.965526,18.858932,19.536535,19.536285,19.761933,19.702319,18.896402,18.659894,18.222474,19.008915,21.143886,20.926050,1.065940,0.002500,0.596142,2.365088,-7.864412,-0.675103,0.370494,3.171004,-7.426992
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2413,2413,20.15456,72.84432,5.199882,4.516778,4.321080,2.658953,5.113997,5.301668,6.419223,5.321604,4.643430,4.444982,3.714938,3.854844,4.139609,4.255815,4.452552,4.649219,5.692389,5.655310,5.644909,5.544761,1.984477,-1.399058,-1.162059,-1.966671,0.370784,-0.669015,-1.446824,-2.163408,-0.672385
2414,2414,20.15456,72.92394,0.122287,0.126717,0.101494,0.111509,0.121749,0.122467,0.145785,0.120626,0.115299,0.114920,0.113067,0.113935,0.112601,0.113587,0.118964,0.121646,0.131579,0.130483,0.128726,0.127383,0.003790,-0.008682,-0.009866,-0.026821,0.010953,-0.006829,-0.008531,-0.032198,0.001020
2415,2415,20.15456,73.00357,0.039415,0.040843,0.032713,0.035941,0.039241,0.039473,0.046989,0.038879,0.037162,0.037040,0.036443,0.036723,0.036293,0.036611,0.038344,0.039208,0.042410,0.042057,0.041490,0.041057,0.001221,-0.002798,-0.003180,-0.008645,0.003530,-0.002201,-0.002750,-0.010378,0.000329
2416,2416,20.15456,73.08319,2.719220,1.370163,0.818687,1.205721,1.316443,1.324201,1.576338,1.304297,1.554290,1.519433,1.138944,1.156694,1.133900,1.152930,1.286330,1.315331,1.422729,1.410885,1.391881,1.408121,0.348568,-0.177500,-0.190301,-0.290008,0.118432,0.202990,-0.167508,-0.423408,0.011034
2417,2417,20.15456,73.16282,0.621228,0.238414,0.112909,0.209801,0.229067,0.230417,0.274289,0.226953,0.303056,0.293731,0.189317,0.193292,0.188440,0.192637,0.223827,0.228873,0.247561,0.245500,0.242193,0.248279,0.093256,-0.039749,-0.041977,-0.050463,0.020608,0.064664,-0.037124,-0.081652,0.001920

In [52]:
df.rename(columns = {"fore3":"fore2013"},inplace = True)
df.rename(columns = {"fore4":"fore2014"},inplace = True)
df.rename(columns = {"fore5":"fore2015"},inplace = True)
df.rename(columns = {"fore6":"fore2016"},inplace = True)
df.rename(columns = {"fore7":"fore2017"},inplace = True)
df.rename(columns = {"fore8":"fore2018"},inplace = True)

df.rename(columns = {"fore33":"fore2(2014)"},inplace = True)
df.rename(columns = {"fore44":"fore2(2015)"},inplace = True)
df.rename(columns = {"fore55":"fore2(2016)"},inplace = True)
df.rename(columns = {"fore66":"fore2(2017)"},inplace = True)
df.rename(columns = {"fore77":"fore2(2018)"},inplace = True)
df.rename(columns = {"fore88":"fore2(2019)"},inplace = True)

In [53]:
df

,Index,Latitude,Longitude,2010,2011,2012,2013,2014,2015,2016,2017,fore2013,fore2(2014),fore2014,fore2(2015),fore2015,fore2(2016),fore2016,fore2(2017),fore2017,fore2(2018),fore2018,fore2(2019),resi1(2013),resi1(2014),resi1(2015),resi1(2016),resi1(2017),resi2(2014),resi2(2015),resi2(2016),resi2(2017)
0,0,24.66818,71.33144,8.475744,8.868568,9.202181,6.023070,10.788374,6.647325,7.387925,5.180296,8.884166,8.598057,7.830453,8.126245,8.882925,8.659365,7.702363,7.670919,8.185880,7.885321,6.282693,6.542841,2.861096,-2.957921,2.235600,0.314438,3.005583,-2.190317,1.478920,1.271440,2.490623
1,1,24.66818,71.41106,24.029778,28.551348,25.866415,21.634459,34.419411,27.361908,40.431847,42.126945,26.120904,25.672259,24.979112,25.923142,28.018026,27.952415,27.760924,29.028016,34.707134,35.449115,37.188905,36.082104,4.486445,-9.440298,0.656118,-12.670923,-7.419811,-8.747152,-1.438766,-12.479432,-13.098929
2,2,24.66818,71.49069,44.831635,66.111168,56.982258,53.003735,70.917908,42.517117,59.181629,73.203232,56.075744,55.768543,58.129522,59.408360,61.362961,59.478376,54.183339,54.683168,57.703159,59.253166,59.790916,59.419399,3.072009,-12.788386,18.845844,-4.998290,-15.500073,-15.149365,16.891244,0.296747,-18.520064
3,3,24.66818,71.57031,59.974419,80.821304,78.956543,63.160561,93.513924,70.203171,74.536720,101.067352,73.821334,72.755257,73.197578,75.229213,80.040701,79.056948,75.083614,75.028924,78.929816,81.143570,83.848908,82.846151,10.660773,-20.316345,9.837530,0.546893,-22.137536,-20.758667,5.026042,4.520227,-26.038428
4,4,24.66818,71.64994,14.653370,19.327524,21.928144,17.899586,19.534035,19.165791,16.531315,26.086885,18.965526,18.858932,19.536535,19.536285,19.761933,19.702319,18.896402,18.659894,18.222474,19.008915,21.143886,20.926050,1.065940,0.002500,0.596142,2.365088,-7.864412,-0.675103,0.370494,3.171004,-7.426992
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2413,2413,20.15456,72.84432,5.199882,4.516778,4.321080,2.658953,5.113997,5.301668,6.419223,5.321604,4.643430,4.444982,3.714938,3.854844,4.139609,4.255815,4.452552,4.649219,5.692389,5.655310,5.644909,5.544761,1.984477,-1.399058,-1.162059,-1.966671,0.370784,-0.669015,-1.446824,-2.163408,-0.672385
2414,2414,20.15456,72.92394,0.122287,0.126717,0.101494,0.111509,0.121749,0.122467,0.145785,0.120626,0.115299,0.114920,0.113067,0.113935,0.112601,0.113587,0.118964,0.121646,0.131579,0.130483,0.128726,0.127383,0.003790,-0.008682,-0.009866,-0.026821,0.010953,-0.006829,-0.008531,-0.032198,0.001020
2415,2415,20.15456,73.00357,0.039415,0.040843,0.032713,0.035941,0.039241,0.039473,0.046989,0.038879,0.037162,0.037040,0.036443,0.036723,0.036293,0.036611,0.038344,0.039208,0.042410,0.042057,0.041490,0.041057,0.001221,-0.002798,-0.003180,-0.008645,0.003530,-0.002201,-0.002750,-0.010378,0.000329
2416,2416,20.15456,73.08319,2.719220,1.370163,0.818687,1.205721,1.316443,1.324201,1.576338,1.304297,1.554290,1.519433,1.138944,1.156694,1.133900,1.152930,1.286330,1.315331,1.422729,1.410885,1.391881,1.408121,0.348568,-0.177500,-0.190301,-0.290008,0.118432,0.202990,-0.167508,-0.423408,0.011034
2417,2417,20.15456,73.16282,0.621228,0.238414,0.112909,0.209801,0.229067,0.230417,0.274289,0.226953,0.303056,0.293731,0.189317,0.193292,0.188440,0.192637,0.223827,0.228873,0.247561,0.245500,0.242193,0.248279,0.093256,-0.039749,-0.041977,-0.050463,0.020608,0.064664,-0.037124,-0.081652,0.001920